###
GET {{base}}/backend/cashpoint/export/sellers/{{cashpoint_secret}}
Accept: application/json

###
GET {{base}}/backend/cashpoint/export/items/{{cashpoint_secret}}
Accept: application/json

###
DELETE {{base}}/backend/seller/limit/{{reset_secret}}
