### export all sellers
GET {{base_path}}/backend/cashpoint/export/sellers/{{cashpoint_secret}}

### export all items
GET {{base_path}}/backend/cashpoint/export/items/{{cashpoint_secret}}

### items arrived / transferred
POST {{base_path}}/backend/cashpoint/confirm/transfer/{{cashpoint_secret}}
Content-Type: application/json

{
	"item_ids" : [1,3]
}

### items sold
POST {{base_path}}/backend/cashpoint/confirm/sold/{{cashpoint_secret}}
Content-Type: application/json

{
  "item_ids" : [1,3],
  "analog_items" : []
}

### sell analog item
POST {{base_path}}/backend/cashpoint/confirm/sold/{{cashpoint_secret}}
Content-Type: application/json

{
  "item_ids" : [],
  "analog_items" : [
    {
      "seller_name": "Mr.Oizo",
      "item_name": "Flat Beat",
      "item_price": 1000
    }
  ]
}
